//
//  HomePresenter.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 14.01.2022.
//  Copyright (c) 2022 Artur Ryzhikh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentWeather(response: Home.Responses.Response)
    func presentError(message: String)
    
}

class HomePresenter: NSObject, HomePresentationLogic {
    
    var builder: HomeViewModelBuilder?
    weak var viewController: HomeDisplayLogic?
    //MARK: Present
    func presentWeather(response: Home.Responses.Response) {
        builder = HomeViewModelBuilder(model: response)
        guard let viewModel = builder?.buildViewModel() else {
            viewController?.displayError(message: "Error constructing View Model from weather data")
            return
        }
        viewController?.displayWeather(viewModel: viewModel)
        
    }
    func presentError(message: String) {
        viewController?.displayError(message: message)
    }
    
}



