//
//  HomeRouter.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 14.01.2022.
//  Copyright (c) 2022 Artur Ryzhikh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func showAlert(message: String)
    func routeToSearch(source: UIViewController, destination: UIViewController)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
   
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    //MARK: Alert
    func showAlert(message: String) {
        viewController?.presentAlert(message: message)
    }
    
    
    
    //MARK: Routing
    
    func routeToSearch(source: UIViewController, destination: UIViewController) {
        let dest = UINavigationController(rootViewController: destination)
        source.presentInFullScreen(dest, animated: true)
        
    }
    
}


//MARK: UITabBarDelegate
extension HomeRouter: UITabBarDelegate {
    func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        guard let source = viewController else {
            return
        }
        routeToSearch(source: source, destination: SearchViewController())
    }
}
