//
//  HomeRouter.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 14.01.2022.
//  Copyright (c) 2022 Artur Ryzhikh. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func showAlert(message: String)
    func navigateToSearch(source: UIViewController, destination: UIViewController)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    //MARK: Alert
    func showAlert(message: String) {
        let alert = UIAlertController(
            title: "Oops! Something went wrong.",
            message: message,
            preferredStyle: .actionSheet)
        alert.addAction(.init(title: "ok", style: .default))
        DispatchQueue.main.async { [weak self] in
            guard let self = self else {
                return
            }
            self.viewController?.present(alert, animated: true)
        }
    }
    //MARK: Navigation
    func navigateToSearch(source: UIViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
    
    //MARK: Passing data
    
    //      func passDataToSomewhere(source: HomeDataStore, destination: inout SomewhereDataStore) {
    //        destination.name = source.name
    //      }
}

//MARK: UITabBarDelegate
extension HomeRouter: UITabBarDelegate {
    func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        guard let source = viewController else {
            return
        }
        let dest = UINavigationController(rootViewController: SearchViewController())
        navigateToSearch(source: source, destination: dest)
    }
}
