//
//  SearchInteractor.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchBusinessLogic {
    func searchCities(named: String)
}

protocol SearchDataStore {
    
}

class SearchInteractor: SearchBusinessLogic, SearchDataStore {
  
    var presenter: SearchPresentationLogic?
    var worker: SearchWorker?
    // MARK: Search Cities
    func searchCities(named: String) {
        guard named.isValid else {
            presenter?.presentCities(response: [])
            return
        }
        let request = Search.Requests.CitiesRequest(cityName: named)
        worker = SearchWorker()
        worker?.getCities(request: request) { [weak self] result in
            guard let self = self else {
                return
            }
            switch result {
            case.failure(let error):
                self.presenter?.present(error: error)
            case.success(let response):
                self.presenter?.presentCities(response: response)
                
               
            }
        }
        
    }
}
