//
//  SearchPresenter.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
enum SearchPresentationError: Error , CustomStringConvertible{
    case build
    var description: String {
        switch self {
        case .build:
            return "Cannont build view model"
        }
    }
}
protocol SearchPresentationLogic {
    func present(error: Error)
    func presentCities(response: [Search.Responses.Place])
    
}

class SearchPresenter: SearchPresentationLogic {
    
    weak var viewController: SearchDisplayLogic?
    var builder: SearchViewModelBuilder? = nil
    
    // MARK: Do something
    func present(error: Error) {
        let message = error.localizedDescription
        viewController?.displayError(message: message)
    }
    func presentCities(response: [Search.Responses.Place]) {
        builder = SearchViewModelBuilder(model: response)
        guard let builder = builder else {
            present(error: SearchPresentationError.build)
            return
        }
        let viewModel = builder.buildViewModel()
        viewController?.displayCities(viewModel: viewModel)
    }
}
