//
//  SearchRouter.swift
//  iOSWeather
//
//  Created by Artur Ryzhikh on 17.01.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic {
    func showAlert(message: String)
    func routeToHome(with coordinates: Coord)
    func navigateToHome(source: SearchViewController?,
                        destination: HomeViewController?)
    
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get set }
    func pass(coordinates: Coord, to destination: inout HomeDataStore?)
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    
    weak var viewController: SearchViewController?
    
    var dataStore: SearchDataStore?
    //MARK: Alert
    func showAlert(message: String) {
        viewController?.presentAlert(message: message)
    }
    //MARK: Route
    func routeToHome(with coordinates: Coord) {
        guard let destinationVC = viewController?
                .presentingViewController as? HomeViewController
        else {
            let message = "No appropriate View Controller to route on"
            viewController?.router?.showAlert(message: message)
            return
        }
        var destionationDS = destinationVC.router?.dataStore
        pass(coordinates: coordinates, to: &destionationDS)
        navigateToHome(source: viewController, destination: destinationVC)
        destinationVC.interactor?.getCityForecast()
    }
    //MARK: Passing data
    func pass(coordinates: Coord, to destination: inout HomeDataStore?) {
        destination?.coord = coordinates
    }
    
    //MARK: Navigation
    func navigateToHome(source: SearchViewController?, destination: HomeViewController?) {
        source?.navigationController?.dismiss(animated: true)
        
    }
    
}
